import { Metadata } from 'next';
import { PageHero } from '@/components/sections/page-hero';

export const metadata: Metadata = {
  title: 'Disclaimers | SpeakStride',
  description: 'Important disclaimers and limitations regarding SpeakStride AI voice training platform. Understand the scope and limitations of our services.',
  openGraph: {
    title: 'Disclaimers | SpeakStride',
    description: 'Important disclaimers and limitations regarding SpeakStride AI voice training platform.',
  },
};

export default function DisclaimersPage() {
  return (
    <>
      <PageHero
        title="Disclaimers"
        description="Important information about the scope and limitations of our services."
      />

      <div className="container mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <div className="max-w-4xl mx-auto prose prose-gray dark:prose-invert prose-lg">
          <div className="mb-8 text-sm text-muted-foreground">
            Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
          </div>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold mb-4">1. General Disclaimers</h2>
            <p className="mb-4">
              The information and services provided by SpeakStride are intended for training and educational purposes only.
              While we strive to provide accurate and helpful AI-powered sales training simulations, users should understand
              the following limitations and disclaimers.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold mb-4">2. AI Technology Limitations</h2>

            <h3 className="text-xl font-semibold mb-3">2.1 Artificial Intelligence Accuracy</h3>
            <p className="mb-4">Our AI-powered voice agents and analysis systems are based on machine learning technologies that:</p>
            <ul className="list-disc pl-6 mb-4">
              <li>May not always provide perfectly accurate responses or assessments</li>
              <li>Are continuously improving but may contain errors or biases</li>
              <li>Should not be considered as substitutes for human judgment</li>
              <li>May interpret speech patterns differently than human evaluators</li>
              <li>Cannot fully replicate the complexity of real human interactions</li>
            </ul>

            <h3 className="text-xl font-semibold mb-3">2.2 Performance Scoring</h3>
            <p className="mb-4">Performance scores and feedback generated by our platform:</p>
            <ul className="list-disc pl-6 mb-4">
              <li>Are algorithmic assessments based on predefined criteria</li>
              <li>May not capture all nuances of sales performance</li>
              <li>Should be used as guidance rather than definitive evaluations</li>
              <li>May vary based on audio quality, accent, or speaking patterns</li>
              <li>Are subject to ongoing refinement and updates</li>
            </ul>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold mb-4">3. Training and Educational Scope</h2>

            <h3 className="text-xl font-semibold mb-3">3.1 Simulation Environment</h3>
            <p className="mb-4">Our training simulations:</p>
            <ul className="list-disc pl-6 mb-4">
              <li>Are artificial scenarios that may not reflect all real-world situations</li>
              <li>Cannot account for every possible customer interaction</li>
              <li>Should be supplemented with real-world training and experience</li>
              <li>May not include all cultural, regional, or industry-specific variations</li>
              <li>Are designed for practice and skill development, not actual sales calls</li>
            </ul>

            <h3 className="text-xl font-semibold mb-3">3.2 Professional Development</h3>
            <p className="mb-4">While our platform can support professional development:</p>
            <ul className="list-disc pl-6 mb-4">
              <li>It is not a complete replacement for comprehensive sales training programs</li>
              <li>Results may vary based on individual learning styles and commitment</li>
              <li>Success depends on consistent practice and application of learned skills</li>
              <li>Additional coaching and mentorship may be necessary for optimal results</li>
            </ul>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold mb-4">4. Technical Service Disclaimers</h2>

            <h3 className="text-xl font-semibold mb-3">4.1 Service Availability</h3>
            <p className="mb-4">Regarding our platform's technical performance:</p>
            <ul className="list-disc pl-6 mb-4">
              <li>We strive for high uptime but cannot guarantee 100% availability</li>
              <li>Service interruptions may occur due to maintenance, updates, or technical issues</li>
              <li>Internet connectivity and device compatibility may affect performance</li>
              <li>Third-party service dependencies may impact functionality</li>
            </ul>

            <h3 className="text-xl font-semibold mb-3">4.2 Data Processing</h3>
            <p className="mb-4">Voice and data processing may be subject to:</p>
            <ul className="list-disc pl-6 mb-4">
              <li>Occasional technical errors or processing delays</li>
              <li>Variations in transcription accuracy due to audio quality</li>
              <li>Temporary data synchronization issues</li>
              <li>Dependencies on third-party AI and cloud services</li>
            </ul>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold mb-4">5. Compliance and Legal Disclaimers</h2>

            <h3 className="text-xl font-semibold mb-3">5.1 Recording Compliance</h3>
            <p className="mb-4">Users are responsible for:</p>
            <ul className="list-disc pl-6 mb-4">
              <li>Ensuring compliance with local recording and privacy laws</li>
              <li>Obtaining necessary consents before using voice recording features</li>
              <li>Understanding their jurisdiction's requirements for voice data processing</li>
              <li>Implementing appropriate organizational policies for training data use</li>
            </ul>

            <h3 className="text-xl font-semibold mb-3">5.2 Industry Regulations</h3>
            <p className="mb-4">Our platform is not specifically designed to ensure compliance with:</p>
            <ul className="list-disc pl-6 mb-4">
              <li>Industry-specific regulations (FINRA, HIPAA, etc.)</li>
              <li>Professional licensing requirements</li>
              <li>Specific certification or accreditation standards</li>
              <li>Regional sales practice regulations</li>
            </ul>
            <p>
              Users should consult with legal and compliance professionals to ensure their use of our platform
              meets all applicable regulatory requirements.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold mb-4">6. Results and Performance Disclaimers</h2>

            <h3 className="text-xl font-semibold mb-3">6.1 Individual Results</h3>
            <p className="mb-4">Training outcomes may vary based on:</p>
            <ul className="list-disc pl-6 mb-4">
              <li>Individual skill levels, experience, and commitment to practice</li>
              <li>Quality and consistency of training session participation</li>
              <li>Application of learned skills in real-world scenarios</li>
              <li>Additional training and development activities</li>
              <li>Personal, professional, and market factors beyond our control</li>
            </ul>

            <h3 className="text-xl font-semibold mb-3">6.2 Business Outcomes</h3>
            <p className="mb-4">We do not guarantee:</p>
            <ul className="list-disc pl-6 mb-4">
              <li>Specific improvements in sales performance or revenue</li>
              <li>Achievement of particular KPIs or business metrics</li>
              <li>Success in any specific sales scenario or market</li>
              <li>Compatibility with all sales methodologies or organizational cultures</li>
            </ul>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold mb-4">7. Third-Party Content and Integrations</h2>
            <p className="mb-4">Our platform may include or integrate with third-party services:</p>
            <ul className="list-disc pl-6 mb-4">
              <li>We are not responsible for third-party content, services, or privacy practices</li>
              <li>Third-party integrations may have their own terms and limitations</li>
              <li>External links are provided for convenience and do not constitute endorsement</li>
              <li>Third-party service availability and functionality may change without notice</li>
            </ul>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold mb-4">8. Intellectual Property Disclaimers</h2>
            <p className="mb-4">Regarding intellectual property and content:</p>
            <ul className="list-disc pl-6 mb-4">
              <li>Training scenarios may be based on general industry practices, not proprietary methods</li>
              <li>AI-generated content is not guaranteed to be original or copyright-free</li>
              <li>Users should ensure their use of our platform doesn't infringe third-party rights</li>
              <li>We make no warranties regarding the intellectual property status of generated content</li>
            </ul>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold mb-4">9. Medical and Health Disclaimers</h2>
            <p className="mb-4">Our platform is not intended for medical or therapeutic purposes:</p>
            <ul className="list-disc pl-6 mb-4">
              <li>Voice analysis features are for training assessment only, not medical diagnosis</li>
              <li>Stress or performance metrics should not be used for health-related decisions</li>
              <li>Users with speech, hearing, or other disabilities should consult professionals</li>
              <li>Any health-related observations should be discussed with appropriate healthcare providers</li>
            </ul>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold mb-4">10. Updates and Changes</h2>
            <p className="mb-4">These disclaimers are subject to updates and modifications:</p>
            <ul className="list-disc pl-6 mb-4">
              <li>We may update these disclaimers as our technology and services evolve</li>
              <li>Continued use of our platform constitutes acceptance of updated disclaimers</li>
              <li>Users are responsible for reviewing disclaimers periodically</li>
              <li>Material changes will be communicated through appropriate channels</li>
            </ul>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold mb-4">11. Contact Information</h2>
            <p className="mb-4">
              If you have questions about these disclaimers or need clarification about the scope
              and limitations of our services, please contact us:
            </p>
            <div className="bg-muted p-4 rounded-lg">
              <p className="mb-2"><strong>Legal Team:</strong> legal@speakstride.com</p>
              <p className="mb-2"><strong>Support:</strong> support@speakstride.com</p>
              <p className="mb-2"><strong>Address:</strong> SpeakStride, Inc.</p>
              <p>1234 Business Ave, Suite 100</p>
              <p>San Francisco, CA 94105</p>
            </div>
          </section>

          <div className="mt-12 p-6 bg-amber-50 dark:bg-amber-950/20 border border-amber-200 dark:border-amber-800 rounded-lg">
            <h3 className="text-lg font-semibold text-amber-800 dark:text-amber-200 mb-2">
              Important Notice
            </h3>
            <p className="text-amber-700 dark:text-amber-300 text-sm">
              By using SpeakStride's services, you acknowledge that you have read, understood, and agree to these disclaimers.
              These disclaimers form an integral part of our Terms of Service and should be read in conjunction with our
              Privacy Policy and other legal documents.
            </p>
          </div>
        </div>
      </div>
    </>
  );
}